### ISSUE TITLE
Reference to quatloo and simoleans

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/documentation#151]
In the [current intro to ERTP](https://github.com/Agoric/documentation/blob/0e4a1c8a79532b3311521fef8c23c6adbcb6beb5/main/getting-started/ertp-introduction.md#security-properties), I can read:

> (after all, quatloos are a very unstable asset, so we wouldn't want to let people deposit quatloos and get credit for simoleans.)

This felt weird to me
because neither quatloos or simoleans have been introduced before
and so i feel it's hard to relate to what is meant

On a more general note, I don't get the reference if there is one. These words were unknown to me before entering Agoric-land. I wonder this is a wide-spread reference (and consequently whether it's  good idea to use them at all if they're meant to reference something shared by culture)

**Comment by DavidBruant** [comment]
I think i remember, but cannot find where, that at some point, people would be trading wood and wool and other sort of "barter-evoking"  things. I think that that could be a more relatable asset names

**Comment by dtribble** [comment]
"quatloo" is I think a Star Trek reference. But saying random things about fictitious assets seems a little strange regardless. "sheep" for "wood" is a Setllers of Catan reference, basically.

I feel like we should minimize or avoid using physical goods in our examples, because of course, we do not and cannot actually ship those around. Hence concert tickets and digital currencies. We should at least have something like "imagine a currency named "simolean".

**Comment by tyg** [comment]
Done.
