### ISSUE TITLE
Document a nicer way to install contracts

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/documentation#24]
[Currently](https://github.com/Agoric/Documentation/pull/22), contract installation is done by:
- creating a file in the middle of the cosmic-swingset repo (hacking the pixel demo, really)
- write the contract content in the file
- expose the contract source code as a property of `home`
- start scenario 3, 2 or 1 of cosmic-swingset

I think a nicer way is possible. Likely [via `home.uploads`](https://github.com/Agoric/cosmic-swingset/blob/master/README.md)

**Comment by michaelfig** [comment]
@DavidBruant feel free to ping me if you need help adapting your demo to the new `ag-solo upload-contract` mechanism.  It should be straightforward (moreso than the latest explanation in [`README-contract`](https://github.com/Agoric/cosmic-swingset/tree/master/lib/ag-solo/contracts/README-contract.md)).

**Comment by michaelfig** [comment]
Hi,

Now (with cosmic-swingset current master) you can start your ag-solo running, and do:

```
./docker/ag-solo upload-contract zoe-coveredCall=./node_modules/\@agoric/ertp/core/zoe/contracts/coveredCall.js
solo [
  'upload-contract',
  '--ag-solo=ws://127.0.0.1:8000/captp',
  'zoe-coveredCall=node_modules/@agoric/ertp/core/zoe/contracts/coveredCall.js'
]
Chain loaded: undefined
Uploading contracts...
Uploading zoe-coveredCall
Success!  See home.uploads~.list()
connection closed
```

and then in the REPL:
```js
command[1] home.uploads~.list()
history[1] ["zoe-coveredCall"]
command[2] home.uploads~.get('zoe-coveredCall')
history[2] [Presence o-62]
```

Using the installation in conjunction with `home.zoe` is up to you.  If you want to use a contractHost contract instead, you'll have to specify `contractHost-...` instead of `zoe-...`.  Of course, the path after the equals sign is just to the top level of your contract, as explained in the README.

**Comment by DavidBruant** [comment]
Super cool, thanks @michaelfig 
I'm going to try this soon and see how to integrate it in the tutorial
