### ISSUE TITLE
Document Comparable

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/documentation#45]
The only thing i could find was here https://github.com/Agoric/ERTP/blob/a7601a0fa1e26f4b2849e3c29d2026ab07331cfc/util/sameStructure.js#L32-L37
but it's used in lots of places (chainmail interfaces, comments, this documentation repo)

**Comment by barbaraliau** [comment]
I haven't been able to find an official documentation for it. We can add it to the documentation.

What about:

"Objects that are `Comparable` must be able to be compared to other objects of its same type, and be less than, equal to, or greater than each other i.e. `Comparable Object A` must be less than, equal to, or greater than `Comparable Object B`."

This may or may not encompass the whole concept. Perhaps @Chris-Hibbert or @katelynsills can weigh in here.

**Comment by Chris-Hibbert** [comment]
From the code you referenced, "A *passable* is something that may be mashalled.  ...  A *comparable* is a passable whose leaves contain no promises. Two comparables can be synchronously compared for structural equivalence."

So a comparable is a javascript object that contains no promises, and can therefore be locally compared for equality with another object.

There's no inherent concept of greater than or less than. The question is whether two local objects represent the same thing. If either contains promises, you can't tell. If both are fullfilled down to Presences and local state, then either they're the same all the way down, or they represent different objects.

**Comment by barbaraliau** [comment]
Ah, this is good to know. I was thinking it was similar to Java Comparables.

What about this then:

"A *passable* is something that may be mashalled. A *comparable* is a
passable whose leaves contain no promises. Two comparables can be
synchronously compared for structural equivalence."

A comparable is a JavaScript object that contains no promises, and can
therefore be locally compared for equality with another object. If either
contains promises, equality is indeterminable. If both are fullfilled down
to Presences and local state, then either they're the same all the way
down, or they represent different objects."

Maybe omit the last sentence since it might bring up more questions. And
this also may leave the question of the definition of 'marshalled'.

**Comment by erights** [comment]
@michaelfig @jfparadis ,
By coincidence, this thread started earlier today. I just saw it.

@barbaraliau ,
I think your text is fine, including the last sentence.

**Comment by tyg** [comment]
Done.
