### ISSUE TITLE
blockchain

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/documentation#5]

**Comment by tyg** [comment]
I'm going to close this without adding it to the Glossary. Right now, the Glossary is aimed at Zoe/ERTP rather than the whole of Agoric. The rest of Zoe/ERTP docs don't really go into detail about blockchain integration yet, and anything we'd put in the Glossary would be short to the point of being facile or long to the point of overwhelming the rest of it. I think it's better people look it up on their own for the moment.
