### ISSUE TITLE
Update ERTP Getting Started with Better Instructions

### ISSUE THREAD

**Issue by katelynsills** [Agoric/documentation#82]
Currently it is just `npm install` and `npm test`. We should mention the Agoric ERTP package now that we have it, and perhaps a few more things.

agoric.com/documentation/ertp/guide/getting-started.html#installation

**Comment by DavidBruant** [comment]
I would remove this "getting started" because i don't think ERTP is really people will "start" with (unlike agoric-cli or Zoe)
I feel like there are 2 ways people will start their interactions with ERTP: they create an issuer or they just received a payment and are unsure what to do with it. I feel the intro can cover this (with links to the guides)

**Comment by katelynsills** [comment]
I like that a lot. We would probably want to remove it entirely until we have a standard wallet API, after which we could have sections like "So you got an issuer, what do you do with it?" and "so you received a payment, here's how you can deposit it"

**Comment by katelynsills** [comment]
The "Getting Started" page was removed in #79. Closing
