### ISSUE TITLE
Documenting Agoric start

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/documentation#86]
I'm trying to create a visual for the different parts created by `agoric start` (and the parts interacting with what's created)

Right now, i'm at:

![Agoric-cli start](https://user-images.githubusercontent.com/165829/75795238-51e77680-5d72-11ea-9d48-0f75db68f809.png)

I know i got the major parts more or less ok
i'm sure i got lots of minor parts super wrong, but i don't know in what way

@michaelfig @Chris-Hibbert (maybe others?), could you comment on this first draft and tell me how to improve this?

Thanks!

A couple questions to get started:
- are all vats run in the fake blockchain?
- when a contract is deployed, is a new vat created or is it eval'ed in an existing vat (and which?)

**Comment by michaelfig** [comment]
> A couple questions to get started:
> * are all vats run in the fake blockchain?

The solo machine has some vats, like the HTTP handler, local spawner (contractHost for solo), wallet.  These are local to the solo vat, even when on a real blockchain.

> * when a contract is deployed, is a new vat created or is it eval'ed in an existing vat (and which?)

Currently evaled in `vat-zoe` or `vat-host`, but will soon be evaluated in a new vat for isolation purposes.  Zoe needs some changes to make this work (which is why we haven't done it yet), as does the dynamic vat mechanism.

For illustration, you can say that the contract is "metered", in that it runs in a restricted execution environment.  Right now, that a separate `evaluate` call within the same vat, but eventually that `evaluate` will be performed in a fresh dynamic vat.

Otherwise, looks like a good diagram!

**Comment by tyg** [comment]
Material moved into [#421](https://github.com/Agoric/documentation/issues/421) which supersedes this.
