### ISSUE TITLE
Document Durable Storage

### ISSUE THREAD

**Issue by 0xpatrickdev** [Agoric/documentation#879]
As a developer, I need to know how to make my contract and its related assets (objects, invitations, etc) durable across updates and restarts. I can see things like `prepare`, `prepareExoClassKit`, `prepareExoClass`, `provideDurableMapStore` used in some of the more recent contract examples, but I'm not entirely sure how they work or when to use them.

**Comment by dckc** [comment]
fixed in #968

https://docs.agoric.com/guides/zoe/contract-upgrade.html#durability

For stores, it has 3 successively more concise idioms, culminating in `zone.mapStore(...)`.

For classes/kits/exos, it mostly just says

> Use `zone.exoClass()` to define state and methods of kinds of durable objects ...

This presumes future work on reference [api-docs](https://github.com/Agoric/documentation/labels/api-docs) will make it easy to find the rest of the zone API.
